language: go
go:
  - master
  - 1.x
deploy:
  edge: true
  provider: releases
  overwrite: true
  file:
    - build/secure-dns*
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.
  token:
    secure: AbVG86jq2lfmqKY/4kZmEesRrnWNlK4cIi+yXzmTSE8I0eU5tVuAoQJxIRKQZzUaeOptoJMDiFte4I1HBXFZwjB9HmxIpGCcm83O4Kr4Wx/VfZB45tjlWWl0Ybt94mvN2SZ81LTlZxkn5OTT+gIv7JG8TPk81rBeCqPhvDkqgh+XTCFRg0Pe7To0zptPWmtNMY3SAZDMY77QZGIyHOXQUlbF/xaPjNIr/HpJ1/ertVS+Lr+/gFG5vm/KXEw+SC2SIfooxLwYwWOzPsVzEEUDWljrpLaibXNlQPH8GgxHrO+ZKLSX9T9rSwv3jDFj9aEbb39qz2A3xUWh1RFh23TY7ON6CHJkhu47kr0k0s8ZlB44k/PAsik8t9b6/JgJcUNyuqMbp/irPl6PLYARqv7zn5V7LykmL26rwP24PP5SimZ9fz7c4i4vCZf04rgRtZ5b5gEL71in7TtN8t5fXgO3bU2LTr89oGmAkLnaLYnzZBBic7z1P7J78vtuQRFZXg+yvY1edwJTpM42wgvCdMeY1lmFjElbSYayMprWeswKGdjxznI4bijfTiUSHwKadq1vdvnACSCLg9NEFAAOs3zYABP/VlL0xFPkLp087J3EvGLKBw0VDWU48p7WjZQWSBH806mjOY+0rk9iPFZt3NBNYhh1EjgxxRoWkZ2iilQje/0=
