name: Build release

on:
  - push
  - pull_request
  - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Display Go version
        run: go version

      - name: Build
        run: make all

      - name: Upload release
        if: github.ref_type == 'tag'
        shell: bash
        run: |
          curl -fSsL \
            -o release.json
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}
          jq '.assets[].id' release.json | xargs -I % curl -fSsL \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/assets/%
          RELEASE_ID=`jq '.id'`
          ls build/secure-dns-* | xargs -I % curl -fSsL \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=% \
            --data-binary @%
